
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 12;
  public static final int THEOREM = 2;
  public static final int PROOF = 3;
  public static final int THEREFORE = 19;
  public static final int ASSUME = 5;
  public static final int LPAREN = 27;
  public static final int RPAREN = 28;
  public static final int NOT = 22;
  public static final int AND = 20;
  public static final int IN = 14;
  public static final int OR = 21;
  public static final int COMMA = 31;
  public static final int QED = 4;
  public static final int IMPLIES = 23;
  public static final int DOT = 32;
  public static final int EOF = 0;
  public static final int BY = 17;
  public static final int TRUE = 15;
  public static final int error = 1;
  public static final int EXISTS = 13;
  public static final int NUMBER = 35;
  public static final int NEQ = 26;
  public static final int EQ = 25;
  public static final int FROM = 18;
  public static final int SUBSET = 9;
  public static final int COLON = 33;
  public static final int UNION = 10;
  public static final int SETDIFF = 34;
  public static final int NOTIN = 8;
  public static final int LBRACE = 29;
  public static final int LET = 7;
  public static final int RBRACE = 30;
  public static final int END = 6;
  public static final int FALSE = 16;
  public static final int INTERSECT = 11;
  public static final int IFF = 24;
  public static final int IDENTIFIER = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "THEOREM",
  "PROOF",
  "QED",
  "ASSUME",
  "END",
  "LET",
  "NOTIN",
  "SUBSET",
  "UNION",
  "INTERSECT",
  "FORALL",
  "EXISTS",
  "IN",
  "TRUE",
  "FALSE",
  "BY",
  "FROM",
  "THEREFORE",
  "AND",
  "OR",
  "NOT",
  "IMPLIES",
  "IFF",
  "EQ",
  "NEQ",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "DOT",
  "COLON",
  "SETDIFF",
  "NUMBER",
  "IDENTIFIER"
  };
}

